# Generated by Django 4.2.4 on 2023-08-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmes', '0001_initial'),
        ('jogos', '0001_initial'),
        ('animes', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('animes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='animes.animes')),
                ('filmes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillmes', to='filmes.filmes')),
                ('jogos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='jogos.jogos')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.series')),
            ],
        ),
    ]
